---
# Add tasks to generate and configure an SSL certificate and a private key here
# Add tasks to configure nginx as a reverse proxy here
# Add vhosts and other necessary files in the files/ and/or templates/ directories as appropriate
# Use handlers to restart nginx if necessary

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA) 
  community.crypto.openssl_privatekey:
    path: "{{ssl_dir}}/nginx-selfsigned.key"
    size: 4096 


- name: Generate a Certificate Signing Request 
  community.crypto.x509_certificate:
    path: "{{ssl_dir}}/nginx-selfsigned.crt"
    privatekey_path: "{{ssl_dir}}/nginx-selfsigned.key"
    provider: selfsigned  


- name: Creating a hard link in sites-enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
 

- name: Copy Nginx configuration file
  ansible.builtin.copy:
    src: files/default
    dest:  /etc/nginx/sites-available/default
  notify: Restart nginx

