---
# Add tasks to automate the steps done during weeks 5 and 6 here
# Use the defaults/ and files/ directories too

- name: Check if the repository directory exists
  ansible.builtin.stat:
    path: "{{root}}/"
  register: repository


- name: Clone the GitHub repository
  ansible.builtin.git:
    repo: https://github.com/EdgeKing810/interns-docker-compose-lamp
    dest: "{{root}}/"
    version: master
  when: repository.stat.exists == False

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: files/Dockerfile
    dest: "{{root}}/bin/webserver/Dockerfile"

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{root}}/docker-compose.yml"

- name: Modify the database connection line in index.php
  ansible.builtin.lineinfile:
    path: "{{ root }}/webroot/index.php"
    regexp: '\$link = mysqli_connect\("mysql", "root", "tiger", null\);' 
    line: "$link = mysqli_connect('mysql', '{{ db_USER }}', '{{ db_password }}', null);"


- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{root}}/.env"
  register: env_file_stat

- name: Copy the .env.sample file
  ansible.builtin.copy:
    src: "{{root}}/.env.sample"
    dest: "{{root}}/.env"
  when: not env_file_stat.stat.exists

- name: Delete the .env.sample file
  ansible.builtin.file:
    path: "{{root}}/.env.sample"
    state: absent
  when: not env_file_stat.stat.exists


- name: Add environment variables to .env
  ansible.builtin.lineinfile:
    path: "{{root}}/.env"
    line: "{{ item.key }}={{ item.value }}"
    create: yes
    regexp: "^{{ item.key }}="  
  loop:
    - { key: 'DB_USERNAME', value: '{{ db_USER }}' }
    - { key: 'DB_PASSWORD', value: "{{ db_password }}" }
    - { key: 'DB_ROOT_PASSWORD', value: "{{ db_rootpassword }}" }
    - { key: 'DB_NAME', value: '{{ db_database }}' }


- name: Run docker-compose to start services
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{root}}/"