- name: Update and upgrade the package list
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
  notify:
    - enable nginx
    - start nginx

